### ISSUE TITLE
some  error in windows10

### ISSUE THREAD

**Issue by asjdf** [AvinashReddy3108/YetAnotherSMSBomber#10]
my command ： py .\bomber.py -N 5 -C 86 -T 1 -t 20 13859817250
error：Traceback (most recent call last):
  File ".\bomber.py", line 156, in <module>
    providers = json.load(open(config, "r"))["providers"]
  File "C:\Users\24385\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa5 in position 1336: illegal multibyte sequence

I fixed this problem by change line 156 from
`providers = json.load(open(config, "r"))["providers"]`
to
`providers = json.load(open(config, "r", encoding='UTF-8'))["providers"]`

but another error came:
Traceback (most recent call last):
  File ".\bomber.py", line 186, in <module>
    else providers["multi"]
  File "C:\Users\24385\Documents\GitHub\YetAnotherSMSBomber\utils.py", line 323, in __init__
    self.client = httpx.Client(http2=True, proxies=self.proxy, verify=VERIFY)
TypeError: __init__() got an unexpected keyword argument 'http2'

how can i make the program work?

**Comment by AvinashReddy3108** [comment]
- What version of Python are you running?
- Did you install the modules in `requirements.txt` via pip?

**Comment by asjdf** [comment]
when  install the modules in requirements.txt via pip :
`WARNING: httpx 0.11.1 does not provide the extra 'http2'`

i use python 3.7

**Comment by asjdf** [comment]
Requirement already satisfied: httpx[http2] in c:\users\24385\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 2)) (0.11.1)
  WARNING: httpx 0.11.1 does not provide the extra 'http2'

**Comment by asjdf** [comment]
well it is my envirment's problem.i uninstall the old httpx and install the new httpx then the  problem is solved

**Comment by AvinashReddy3108** [comment]
@asjdf Good to know, I'll update the requirements to prevent this in future.
