### ISSUE TITLE
11 digit number are invalid mobile

### ISSUE THREAD

**Issue by lcxone1** [AvinashReddy3108/YetAnotherSMSBomber#2]
In Germany and China the mobile number are 11 digits, which don't work with it. How can I fix it?
![image](https://user-images.githubusercontent.com/57232036/78919612-741b9500-7a92-11ea-8441-c73e6ece2ab1.png)

**Comment by AvinashReddy3108** [comment]
It's easy to increase the max length of the phone number, but unfortunately, I don't have any German/Chinese APIs in this script yet.

**Comment by AvinashReddy3108** [comment]
https://github.com/AvinashReddy3108/YetAnotherSMSBomber/blob/master/bomber.py#L17
Should fix your issue, re-open this issue if it has not.
