### ISSUE TITLE
Proxy limitation error

### ISSUE THREAD

**Issue by leonardyhuang** [AvinashReddy3108/YetAnotherSMSBomber#4]
I got this error, what is the limitation? Can I use VPN? Thanks.

**Comment by AvinashReddy3108** [comment]
@leonardyhuang Can you post some screenshots to further explain the issue?

**Comment by leonardyhuang** [comment]
Here you go:
<img width="380" alt="Screenshot 2020-06-03 at 21 34 25" src="https://user-images.githubusercontent.com/22125998/83642969-14e58700-a5e2-11ea-8bac-6496f86799c5.png">

I think I have found why, it's the limitation from `https://gimmeproxy.com/api/getProxy?curl=true&protocol=http&supportsHttps=true`, see https://github.com/AvinashReddy3108/YetAnotherSMSBomber/blob/9f13752bb72798ecba8c812b39e5580857e21814/bomber.py#L78.

**Comment by AvinashReddy3108** [comment]
@leonardyhuang I see, nice work.
Will change the API used to fetch proxies.
And yes, you can use VPN. (No extra steps involved.)
