### ISSUE TITLE
NOT WORKING

### ISSUE THREAD

**Issue by Itrix256** [AvinashReddy3108/YetAnotherSMSBomber#5]
Hi ive been trying out this bomber I am kind of new,
It says it has the option so send international,
python3 bomber.py  --sms 500 --country 61 (My phone Number)
I did that to try it on my self and it was saying they were successfully sent but nothing happened please try and help me.
Im kind of new aswell.

**Comment by he1ox** [comment]
you should try just python3 bomber.py --country (COUNTRY) TARGET
sms is set to 30 by default

**Comment by he1ox** [comment]
> Hi ive been trying out this bomber I am kind of new,
> It says it has the option so send international,
> python3 bomber.py --sms 500 --country 61 (My phone Number)
> I did that to try it on my self and it was saying they were successfully sent but nothing happened please try and help me.
> Im kind of new aswell.

you should try just python3 bomber.py --country (COUNTRY) TARGET
sms is set to 30 by default

**Comment by Itrix256** [comment]
I got an sms saying ICQ New: 6***** - your code

**Comment by he1ox** [comment]
Yep, thats how it works. :) Its just spam

**Comment by AvinashReddy3108** [comment]
@he1ox As it was meant to be 😜.

**Comment by he1ox** [comment]
Hey, @AvinashReddy3108 , is this script registering the target's phone to a telephone service that generates expenses? or its just the spam?
Best regards

**Comment by AvinashReddy3108** [comment]
@he1ox Just the spam, no expenses occured.

**Comment by Itrix256** [comment]
Ahhh I see thankyou a lot unfortunately only three messages send in +61
bombing but I see how it works.

**Comment by AvinashReddy3108** [comment]
@Itrix256 That's because I don't have many APIs for bombing numbers of that region code.

**Comment by voolguy84** [comment]
@AvinashReddy3108 Not working for U.S. only getting 2 or 3 texts the script is crafted well only thing is you need to get API's for the U.S.

**Comment by AvinashReddy3108** [comment]
@voolguy84 Yes. In projects like this, they move on to newer, more secure APIs to prevent us from abusing it, and hence is a difficult job to keep it updated while being open-source.
