### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by zenphixiia** [AvinashReddy3108/YetAnotherSMSBomber#7]
i am getting this message:

  File "bomber.py", line 111
    f"Target: {target} | Threads: {no_of_threads} | SMS-Bombs: {no_of_sms}"
                                                                          ^

**Comment by AvinashReddy3108** [comment]
@zenphixiia Are you sure that's the complete error message?

**Comment by zenphixiia** [comment]
oh my bad here is the full error message:

  File "bomber.py", line 111
    f"Target: {target} | Threads: {no_of_threads} | SMS-Bombs: {no_of_sms}"
                                                                          ^
SyntaxError: invalid syntax

**Comment by AvinashReddy3108** [comment]
@zenphixiia
Strange, it works fine for me.
Can you send me the command you used to run this script like..

`./bomber.py 7780xxxxxxx -N 9999999`

**Comment by zenphixiia** [comment]
python3 bomber.py --help

  File "bomber.py", line 111
    f"Target: {target} | Threads: {no_of_threads} | SMS-Bombs: {no_of_sms}"
                                                                          ^
SyntaxError: invalid syntax

**Comment by zenphixiia** [comment]
i apologize for my stupidity, i have managed to get passed this error and have managed to send the attack but for some reason it isnt going through, i have tried my number and still havent gotten any spam messages

**Comment by AvinashReddy3108** [comment]
@zenphixiia Do read this: https://github.com/AvinashReddy3108/YetAnotherSMSBomber/issues/5#issuecomment-670832597
